version: "3.5"
services:
  omim:
    tty: true
    container_name: omim
    image: namxle/omim-crawler:latest
    volumes:
      - ./:/home/ubuntu/omim-crawler
    environment:
      - INPUT_FILE=batch-01
    entrypoint: ["/home/ubuntu/omim-crawler/run.sh"]
  